spring:
  cloud:
    gateway:
      routes:
        - id: currency-exchange-service
          uri: lb://currency-exchange-service
          predicates:
            - Path= /currency-exchange/**
        - id: currency-conversion-service
          uri: lb://currency-conversion-servic
          predicates:
            - Path= /currency-conversion/**
server:
  port: 8765
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
