spring:
  config:
    active:
      on-profile: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/books
    username: postgres
    password: q1w2e3r4t5
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
---
spring:
  config:
    active:
      on-profile: uat
