spring:
  config:
    active:
      on-profile: dev
server:
  port: 8084
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
---
spring:
  config:
    active:
      on-profile: uat
