spring:
  config:
    active:
      on-profile: dev
limits-service:
  minimum: 2
  maximum: 998
server:
  port: 8080
---
spring:
  config:
    active:
      on-profile: uat
limits-service:
  minimum: 10
  maximum: 990
